name: build-test

on:
  pull_request:
  push:
    branches:
      - main

env:
  DATABASE_URL: 'postgresql://prisma:prisma@localhost:5432/prisma?schema=mogami'
  SOLANA_RPC_ENDPOINT: 'http://localhost:8899'

jobs:
  build:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: prisma
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      solana:
        image: solanalabs/solana:v1.9.9
        ports: ['8899:8899', '8900:8900']
        options: --entrypoint="solana-test-validator"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node-version: [14.x]
        operating-system: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn build
      - run: yarn nx e2e api-e2e
